cities = [
    "tokyo",
    "delhi",
    "shanghai",
    "são paulo",
    "mumbai",
    "beijing",
    "cairo",
    "dhaka",
    "mexico city",
    "osaka",
    "karachi",
    "chongqing",
    "istanbul",
    "buenos aires",
    "kolkata",
    "lagos",
    "kinshasa",
    "manila",
    "rio de janeiro",
    "guangzhou",
    "lahore",
    "shenzhen",
    "bangalore",
    "moscow",
    "tianjin",
    "jakarta",
    "london",
    "lima",
    "bangkok",
    "new york city",
    "durham"
]
