weekdays = {
    0: 'Monday',
    1: 'Tuesday',
    2: 'Wednesday',
    3: 'Thursday',
    4: 'Friday',
    5: 'Saturday',
    6: 'Sunday',
    7: 'Monday',
    8: 'Tuesday',
    9: 'Wednesday',
    10: 'Thursday',
    11: 'Friday',
    12: 'Saturday',
}